usage() added.
Signed-off-by: Alexander GQ Gerasiov <gq@cs.msu.su>

diff --git a/nanoca b/nanoca
--- a/nanoca
+++ b/nanoca
@@ -1,4 +1,5 @@
 #!/bin/sh
+set -e
 
 # Basic configs
 BASE="/home/ca/openssl"
@@ -12,6 +13,8 @@ CERT_KEY="rsa:2048"
 if [ -f "${HOME}/.nanoca" ];then
 	. "${HOME}/.nanoca"
 fi
+
+COMMAND_NAME="nanoca"
 
 # Create certificate request.
 create_cert(){
@@ -79,10 +82,18 @@ show_text(){
 	openssl x509 -in "${BASE}/$1" -text
 }
 
+usage(){
+	echo "$COMMAND_NAME operation [parameter]" >&2
+	echo "Operations could be:"
+	echo "init <path>"
+	echo "create <cert-name>"
+	echo "sign <cert-name>"
+	echo "help"
+}
 
 parse_opt(){
 if false;then
-	local TEMP=$(getopt -o ab: --long longa,longb: -n nanoca -- "$@")
+	local TEMP=$(getopt -o ab: --long longa,longb: -n "$COMMAND_NAME" -- "$@")
 	eval set -- "$TEMP"
 	while true; do
 		case "$1" in
@@ -95,7 +106,7 @@ if false;then
 fi
 
 	if [ $# -eq 0 -o $# -gt 2 ];then
-		echo "Parse error!" ; exit 1 ;
+		echo "Parse error!" ; usage; exit 1 ;
 	fi
 
 	COMMAND="$1"
@@ -114,5 +125,6 @@ case "$COMMAND" in
 	create-ca)	create_ca ;;
 	create)		create_cert "$PARAMETER";;
 	sign)		sign_cert "$PARAMETER";;
-	*)		echo "Parse error" ;;
+	help)		usage ;;
+	*)		echo "Parse error!"; usage; exit 1 ;;
 esac
